name: iod
description: A new Flutter package project.
version: 0.0.1-alpha
repository: https://github.com/yohantsn/IoD


environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

