name: iod
description: The objective of this package is provide a simple way to do the Dependency Injection.
version: 0.0.1
homepage: https://github.com/yohantsn

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

